---
# Workflow name
name: Tests

# Triggers
on: push

# Jobs included in workflow (jobs run in parallel)
jobs:

  # Job name
  build:

    # Defines variations of build environment
    strategy:
      matrix:

        # Build with each main operating system
        os: [macos-latest, windows-latest]

        # Build with oldest and newest compatible Python versions
        python-version: ["3.7", "3.10"]

    # Job runner
    runs-on: ${{ matrix.os }}

    # Job steps
    steps:

      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Set up each Python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install flake8 mypy pytest

      # Run tests
      - name: Lint
        run: flake8 src/iqtester tests
      - name: Type Check
        run: mypy src/iqtester tests
      - name: Run Tests
        run: pytest -v

      # Launch iqtester in order to view output in GH Action
      - name: Install iqtester in editable mode
        run: python -m pip install -e .
      - name: Launch Game & Quit
        # Use here string (<<<) to pass quit option (q) to iqtester program
        run: python -m iqtester <<< 'q\n'
      - name: Take Screenshot
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'